# pytest.ini
[pytest]
pythonpath = src
# testpaths = tests  # Commented out to allow conftest.py to be discovered
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 隐藏警告信息
addopts = --disable-warnings
asyncio_mode = auto